# Generated by Django 2.2.12 on 2020-05-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cseform',
            fields=[
                ('expertid', models.IntegerField(primary_key=True, serialize=False)),
                ('expertname', models.CharField(max_length=50)),
                ('formdomainlevel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='amg1formdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formid', models.CharField(max_length=8)),
                ('response_one', models.CharField(max_length=3)),
                ('response_two', models.CharField(max_length=3)),
                ('response_three', models.CharField(max_length=3)),
                ('response_four', models.CharField(max_length=3)),
                ('expertid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crrs_app.cseform', verbose_name='expert id')),
            ],
        ),
    ]
