# Generated by Django 2.2.12 on 2020-05-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crrs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amg1formdb',
            name='messages',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='amg1formdb',
            name='formid',
            field=models.CharField(choices=[('amg1', 'AMG 1')], default='amg1', max_length=8),
        ),
        migrations.AlterField(
            model_name='amg1formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg1formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg1formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg1formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
    ]
