# Generated by Django 2.2.12 on 2020-05-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crrs_app', '0002_auto_20200509_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amg1formdb',
            name='messages',
        ),
    ]
