# Generated by Django 2.2.12 on 2020-05-09 14:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crrs_app', '0003_remove_amg1formdb_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='amg1formdb',
            name='messages',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
