# Generated by Django 2.2.12 on 2020-05-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crrs_app', '0005_amg1formdb_unique_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amg1formdb',
            name='unique_identifier',
        ),
    ]
