# Generated by Django 2.2.12 on 2020-05-14 18:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crrs_app', '0007_auto_20200511_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amg1formdb',
            name='feedback',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
