# Generated by Django 2.2.12 on 2020-06-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crrs_app', '0009_amg2formdb_amg3formdb_amg4formdb_amg5formdb_amg6formdb_amg7formdb_ammil2formdb_ammil3formdb_ammil4fo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cseform',
            new_name='cseformdb',
        ),
    ]
