# Generated by Django 2.2.12 on 2020-06-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crrs_app', '0011_auto_20200625_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cseformdb',
            name='expertname',
        ),
        migrations.AlterField(
            model_name='cseformdb',
            name='formdomainlevel',
            field=models.CharField(choices=[('', '--Select Domain--'), ('am1', 'Asset Management'), ('cm2', 'Controls Management'), ('ccm3', 'Control Change Management'), ('vm4', 'Vulnerability Management'), ('im5', 'Incident Management'), ('scm6', 'Service Continuity Management'), ('rm7', 'Risk Management'), ('edm8', 'External Dependancies Management'), ('ta9', 'Training Awareness'), ('sa10', 'Situational Awareness')], default='', max_length=100),
        ),
    ]
