# Generated by Django 2.2.12 on 2020-06-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crrs_app', '0015_auto_20200626_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amg1formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg1formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg1formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg1formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg2formdb',
            name='response_five',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg5formdb',
            name='response_five',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg5formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg5formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg5formdb',
            name='response_seven',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg5formdb',
            name='response_six',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg5formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg5formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg6formdb',
            name='response_five',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg6formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg6formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg6formdb',
            name='response_seven',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg6formdb',
            name='response_six',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg6formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg6formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg7formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg7formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='amg7formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ammil2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ammil2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ammil2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ammil2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ammil3formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ammil3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ammil3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ammil3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ammil4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ammil4formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ammil4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ammil5formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ammil5formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg1formdb',
            name='response_five',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg1formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg1formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg1formdb',
            name='response_six',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg1formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg1formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg2formdb',
            name='response_eight',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg2formdb',
            name='response_five',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg2formdb',
            name='response_nine',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg2formdb',
            name='response_seven',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg2formdb',
            name='response_six',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg2formdb',
            name='response_ten',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg3formdb',
            name='response_five',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg3formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg3formdb',
            name='response_six',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmg3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmmil2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmmil2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmmil2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmmil2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmmil3formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmmil3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmmil3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmmil3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmmil4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmmil4formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmmil4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmmil5formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ccmmil5formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg1formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg1formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg2formdb',
            name='response_eight',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg2formdb',
            name='response_five',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg2formdb',
            name='response_nine',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg2formdb',
            name='response_seven',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg2formdb',
            name='response_six',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg2formdb',
            name='response_ten',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmg4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmmil2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmmil2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmmil2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmmil2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmmil3formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmmil3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmmil3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmmil3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmmil4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmmil4formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmmil4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmmil5formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cmmil5formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmg1formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmg1formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmg1formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmg2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmg3formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmg3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmg3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmg3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmg4formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmg4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmg4formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmg4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmg5formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmg5formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmmil2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmmil2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmmil2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmmil2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmmil3formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmmil3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmmil3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmmil3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmmil4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmmil4formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmmil4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmmil5formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='edmmil5formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img1formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img1formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img1formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img1formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img2formdb',
            name='response_eight',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img2formdb',
            name='response_five',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img2formdb',
            name='response_nine',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img2formdb',
            name='response_seven',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img2formdb',
            name='response_six',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img4formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img4formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img5formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img5formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='img5formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil2formdb',
            name='response_five',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil3formdb',
            name='response_five',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil3formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil3formdb',
            name='response_seven',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil3formdb',
            name='response_six',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil5formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='immil5formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmg1formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmg1formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmg1formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmg2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmg2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmg2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmg2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmg3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmg4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmg4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmg5formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmg5formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmmil2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmmil2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmmil2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmmil2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmmil3formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmmil3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmmil3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmmil3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmmil4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmmil4formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmmil4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmmil5formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='rmmil5formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='sag1formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='sag1formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='sag1formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='sag2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='sag2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='sag3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='sag3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='sag3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='samil2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='samil2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='samil2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='samil2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='samil3formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='samil3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='samil3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='samil3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='samil4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='samil4formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='samil4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='samil5formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='samil5formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg1formdb',
            name='response_five',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg1formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg1formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg1formdb',
            name='response_seven',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg1formdb',
            name='response_six',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg1formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg1formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg3formdb',
            name='response_five',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg3formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg4formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmg4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmmil2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmmil2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmmil2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmmil2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmmil3formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmmil3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmmil3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmmil3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmmil4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmmil4formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmmil4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmmil5formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='scmmil5formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tag1formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tag1formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tag1formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tag1formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tag2formdb',
            name='response_five',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tag2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tag2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tag2formdb',
            name='response_seven',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tag2formdb',
            name='response_six',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tag2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tag2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tamil2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tamil2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tamil2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tamil2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tamil3formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tamil3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tamil3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tamil3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tamil4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tamil4formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tamil4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tamil5formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tamil5formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmg1formdb',
            name='response_five',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmg1formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmg1formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmg1formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmg1formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmg2formdb',
            name='response_five',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmg2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmg2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmg2formdb',
            name='response_six',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmg2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmg2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmg3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmg3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmg3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmg4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmmil2formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmmil2formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmmil2formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmmil2formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmmil3formdb',
            name='response_four',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmmil3formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmmil3formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmmil3formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmmil4formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmmil4formdb',
            name='response_three',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmmil4formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmmil5formdb',
            name='response_one',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmmil5formdb',
            name='response_two',
            field=models.CharField(choices=[('', '--Select a Response'), ('yes', 'YES'), ('no', 'NO')], default='', max_length=6),
        ),
    ]
