# Generated by Django 2.2.12 on 2020-06-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crrs_app', '0016_auto_20200626_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='amg1formdb',
            name='amg1_complete',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=''),
        ),
        migrations.AddField(
            model_name='amg1formdb',
            name='amg1_incomplete',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=''),
        ),
    ]
