# Generated by Django 2.2.12 on 2020-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crrs_app', '0018_auto_20200627_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amg1formdb',
            name='amg1_complete',
            field=models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='amg1formdb',
            name='amg1_incomplete',
            field=models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], default=1, null=True),
        ),
    ]
