# Generated by Django 2.2.12 on 2020-06-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crrs_app', '0023_auto_20200627_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='amg1formdb',
            name='amg1_complete',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], default=1),
        ),
        migrations.AddField(
            model_name='amg1formdb',
            name='amg1_incomplete',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], default=1),
        ),
    ]
