# Generated by Django 2.2.12 on 2020-06-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crrs_app', '0024_auto_20200627_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amg1formdb',
            name='amg1_incomplete',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
