# Generated by Django 2.2.12 on 2020-06-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crrs_app', '0025_auto_20200627_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amg1formdb',
            name='amg1_complete',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
