# Generated by Django 2.2.12 on 2020-06-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crrs_app', '0027_auto_20200627_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='amg2formdb',
            name='amg2_complete',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=1),
        ),
        migrations.AddField(
            model_name='amg2formdb',
            name='amg2_incomplete',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
